[build]
  command = "npm run build"
  publish = "_site"
  NODE_ENV = "10.15.3"

[dev]
    command = "npm run dev"
    targetPort = 8081

[[edge_functions]]
function = "eleventy-edge"
path = "/*"

[[edge_functions]]
function = "lastfm"
path = "/lastfm"