[build]
  command = "npm run build"
  publish = "dist"
  ignore = "exit 0"
  NODE_OPTIONS = "--max_old_space_size=4096"

[dev]
  command = "npm run start"
  targetPort = 8085

[[edge_functions]]
  function = "eleventy-edge"
  path = "/*"

[functions]
  node_bundler = "esbuild"
