[build]
  command = "npm run build"
  publish = "_site"

[dev]
  command = "npm run dev"
  targetPort = 8085

[[edge_functions]]
  function = "eleventy-edge"
  path = "/*"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
  include = ["LASTFM_API"]
